version: '3.8'

services:
  database:
    image: mongo
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - database
  go-server:
    container_name: go-server
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
      - DB_COLLECTION_NAME=${DB_COLLECTION_NAME}
    networks:
      - database
      - frontend
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - go-server
    links:
      - go-server
    networks:
      - frontend
networks:
  frontend:
    name: frontend_network
    driver: bridge
  database:
    name: database_network
    driver: bridge